language: node_js
dist: jammy
node_js: 16
cache: npm

stages:
  - lint
  - test
  - find-missing

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-plugin-node16
      script: npm run test:unit
      node_js: '16'
    - <<: *test
      name: test-plugin-node18
      node_js: '18'

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- ava

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- core

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- css-modules

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- es20XX

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- lodash-fp

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- mocha

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- prettier

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- react
