language: node_js
dist: jammy
node_js: 16
cache: npm

stages:
  - lint
  - test
  - find-missing

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-plugin-node16
      script: npm run test:unit
      node_js: 16
    - <<: *test
      name: test-plugin-node18
      node_js: 18

    - &find-missing
      stage: find-missing
      name: find-missing-ava
      env: CONFIG=ava
      script: npm run find-missing -- $CONFIG
    - <<: *find-missing
      name: find-missing-core
      env: CONFIG=core
    - <<: *find-missing
      name: find-missing-css-modules
      env: CONFIG=css-modules
    - <<: *find-missing
      name: find-missing-es20XX
      env: CONFIG=es20XX
    - <<: *find-missing
      name: find-missing-lodash-fp
      env: CONFIG=lodash-fp
    - <<: *find-missing
      name: find-missing-mocha
      env: CONFIG=mocha
    - <<: *find-missing
      name: find-missing-prettier
      env: CONFIG=prettier
    - <<: *find-missing
      name: find-missing-react
      env: CONFIG=react
