sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: AK55iSu4YAm5kf0s8sn+Icu+dSoRJ2DO44lncUq63U2w3xNVzCjRPa/M7zrjEE9W0fWN87sPFFMjgmYMJ2iqaeSTLmq9E31GS9m5/gL6b6EK2RVjgWEpEE0cw2f0woxLhVdxSFhiasOtRplVmVHUp7Ps0Z4G2s/Cd7kYHPpbZJBXXB6cicKXex+4hxlH35iWgs/+AXZnfiZuUqoG3T2PoOTYEnlIMUwpQAs37ap3dqawhr58BdP73gL9ZoOaEsXqB2JnyIG9ZLNt7cgtrC8e+9dLK58vVkE9VRHGqW4y0Y0GW0nwRXhN/zP70huGcoLksS7q+1nan3IfJ02E4v0AdW1bIhclL08OOn+mN3xZbZOVny3KZDInhu0p/o/ydnEn1f/1/1mzaBeZhR8PYqMwoAKVH7VTtUu7fJJiCFrs65GnNL3w6IsVfYLEmL4BYv9x9l0l5Qu8uC9QGxSCAhSSLAznDVo30/PGWbpQSaWvBB61kfTDZ5dKKqnabWo6JYeqK7fhkeyJBsG4A6A5SG2zvSS2z2LAomhzjG7lrf+scpRDL4dcLZv96tiEXX1tjsnk9VWoUjGNSyawjGP1Nny8tzV8xf31Zh3cqllFX1H7FQKb4bMhCY9pJoz6C7zMb8fMf8eBLpqeIaQXSISYTWlLGjy5Nogign5IZ5S+5NbaQvU=
  on:
    tags: true
    repo: CoorpAcademy/eslint-plugin-coorpacademy
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
