sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: aXaKjvGOHcMpN72APBdzfIjteBM4TjZQOxIiolby8v6hD9soMRyzHfJUN7F3ssnQVlNC8sEx9aV84T1d8kmyoYd+8xQ19KfDKvgK0QulpkDhhoFed/HDfO+Gtjh2aJdC7K1Bz8DF1h+MigCwFDkfwhT5Ri4ufbfh62vFsIlvaM2Z1Do3BFIZE56PhGhLsSbmvxuDeujyXZX16ppEbiQAmABNQ/bWSBKPrrphyOyhp+WoNPWGoz9yaR333OKHld/t08NtoVoBVz1Tve3xO7rsFKk8fJ3t8uCyOpNZGXp+PnNB6xEYDy2JByQP/U7nJl1e8lRKM+FHgNt+fNiSfQoOVtmxjaY8lCzjICMQzOG/jA8lQko0xO8/cgsJha6sWceNJC4NnaddCaGEM6BaQSEh0guSGqePXpeGsj9U2DWdSuQA3XPEjjCYdJEbpw/kj1LdUgMLDoCm7OL7QaLAUHbBlO3uy6vcfQWUEmJdGCAyUUJ/otJH67lcdR2va+SZ8mxLUSx8ANZvbBR9cHGbR4jRP1h2EzOJGdclLeFNYnp3xltp1ZldX78ma3881OIgp98SAJSQYLpDEJq2ieMLWOoUJD61n8xPL/7xHpvDnUbPxKkcCXb4s75WjU6fy/MwrfgrEBll+/GQWG9dPJZiDY1c0IsLEWKMCRzuFY7pbwE3SfA=
  on:
    tags: true
    repo: CoorpAcademy/eslint-plugin-coorpacademy
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
