sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: PJla9tFeHK7bZYcrPs1BGZFAn5dzQRInV8cEdKn2s3Q423wGvjmu5LaNG9dwl7IbIEFbVJP4OlaMb3uj1H0PKmlXVb6WLTOA7EszHW5/kHu48qESHzuQdJMhM/ePuFffLyu7zjRvmegrwjGv0QmDTgGDsY4NWSKDpdHwXgOTaRPV9D9DPBa2TerM23CYPf0wNUm+f5Lgq0DESQOOoCmIpPHZtFhe2vTXrLSOGJk8fViNdpdqQPv4wFKe+0qMLd//kWVqjBloWcpa26goSdi5mp4gp+uQLL32R+DJcdcyRtq2++eD7vdJk7UGuizQygDOjMoM6y623M5F5TKxOjpvczrOolgo16wKtvNntONl0pl1fEz9q/slufXSK0f+H9Avy/Sv+fSmwC8+/fatOXcvsdbRao9oXVqOxLxA4Z02Bew7LAtiRcu6UYCINo9xCvyKjLqSrKkOK/jACSgyRNtjYRHPxdOf3F/1x5kEPU2K0Tnym9zusIi1wS0t+0lUk3f4UFxcXMVQP4hEPvORib4y75bryFjyuJ31A/ZiYZmE7xp28JFQug7LHVFmRwOz+qduhIXKyS2hgasVV3TpAdoeKFZ6UZz8GFdRhGgVwbeoZJNxlRNyF6qEky89Cfcl/AK6bFxCXggOs5AvXiNsWGS11o/PzhaYcmSvduasPnDkBIQ=
  on:
    tags: true
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
