language: node_js
node_js:
- '8'
- '10'
- '12'
sudo: false
env:
  matrix:
    - STEP='lint'
    - STEP='test:unit'
    - STEP='find-missing:ava'
    - STEP='find-missing:core'
    - STEP='find-missing:css-modules'
    - STEP='find-missing:flowtype'
    - STEP='find-missing:lodash-fp'
    - STEP='find-missing:mocha'
    - STEP='find-missing:prettier'
    - STEP='find-missing:react'

script:
  - npm run $STEP

cache: npm
