sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: KOt4kK8vzchqGbOHuNtV/1p+zOGHWOVimyeKRyTnZKI0LHzd9JhaPf/QVbrnPVcdCVmPxXC/KbWKrW+ZdyHPNOITjxDZSjaMX8y0W7kUBrlC6KDL32yooc7io+E1BQAuCmAlSwdoRI3MDj8AfSsFMHZcWcsLw9t3p+zZvtaZhflP8DmS1vZy8lqOf38rjYp8ZCTnWuUfe49q6zhZ5mkJ/m9FC+yCtpPG/EdvG5KSOtgJ1vf9C7l/9myqCf9c9ztUsYSy6yAT9xO3cWtmx3NeC8a+hfCJOJ8jvVdNHVjJCiDZRs+4Lozz7xt56JHQ01GuvEerzcJ99otrIjt76GPpCS29iLx+9+J0zm3ZHMFV0Mv3AfozRHvLTGSyARnZNAPplT+EFjsH9UfcWtpiv6DNO8RkhXJOjq1KOWLgsfWA2DMPeHteE5qVClyWoGxFtmFU1ZN7an2ZYEmd3ZuPSod1lVazXZy5S4BWR+THeRR7oxhGT/fzn62BdquMGhu2soGiHC//ny3m7AToudkolgp9wpPXO5ScCHLzZiIEFBK69poMk2waI0iR7dSLAtrY0K1U4VQQkdH3oQv5U2lHcSXvnAZGZwsu9GcN38X32bRKz+8/qyVhbhMrCBQP1pcBTC97wHnaulieLfgh5bR3YcGrv8IZSJKJ8t1xYfagUZ/BktE=
  on:
    tags: true
    repo: CoorpAcademy/eslint-plugin-coorpacademy
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
