language: node_js
node_js:
- '8'
- '10'
- '12'
sudo: false
cache: npm
env:
  matrix:
    - 'MISSING_SCOPE=ava'
    - 'MISSING_SCOPE=core'
    - 'MISSING_SCOPE=css-modules'
    - 'MISSING_SCOPE=flowtype'
    - 'MISSING_SCOPE=lodash-fp'
    - 'MISSING_SCOPE=mocha'
    - 'MISSING_SCOPE=prettier'
    - 'MISSING_SCOPE=react'

stages:
  - lint
  - test
  - find-missing

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint
      node_js: '10'
      env: 'MISSING_SCOPE=none'
    - stage: test
      name: test-plugin
      script: npm run test:unit
      env: 'MISSING_SCOPE=none'

    - stage: find-missing
      name: find-missing-plugins
      script: npm run find-missing:$MISSING_SCOPE
      node_js: '10'
