sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: O77PO/4g8RYj65t+z2YiMFa2fiYFZlk90vvC5puZPWNl/O8DXeNFssHPR5irmb41ivalLkPsBYziZVFeEDMX4mtMIKMXryleosXXWqa/jJ7hwrgtQn5txtw93vplfjKTvojYNpZShFjrKUvAoWmguaqBtIVVTytkZs0RRBL3ng63fs/eDkO55mHxv/YfOquychqr+FHSZXV4QniKPyV9BtCd2JYFog6Q5EBdeNlLWsTt2rfHGJnaFpiXCDuHttOLr8ccKuGU+SAsMt26zfvYNfaNOOWqZPC1ABZmPHTi543LdskyN6XDnhrs2Iy6kXS9V4LdzWddx+qTh80bYN+dFgHgXd0rquDOANAP7oCuzAP/f4nXdEGL7syp5KxYDwd4j26HLXuNJPafK2eKm0IQZNoMUYnRfRMPN925PHYFNcEEKSyE/6uK1fUZlqpS/WGv4LdB+wFXymyBob58NmE2errgMmV2uXTGAbHgd+M6xQ++G6W2rwBfaxrHfqXore6vVEyyB+fEem5qI7vo0ejevQBwkyy1Cc/h7rBjH226erSzJXWymyz08F0eyds6cYBa/OPC+pdiV05+E2qNw0KpKlIk5+ptrUly9lWlqwFHM5nPZYRpHiy7AhSNJ82uf8Fn7j2XNpciu2TSatCvBSsTVwDk+P5k0R/C2SpiOJPx7Lc=
  on:
    tags: true
    repo: CoorpAcademy/eslint-plugin-coorpacademy
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
