language: node_js
sudo: false
node_js: '10'
cache: npm

stages:
  - lint
  - test
  - find-missing

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-plugin-node10
      script: npm run test:unit
      node_js: '10'
    - <<: *test
      name: test-plugin-node12
      node_js: '12'
    - <<: *test
      name: test-plugin-node8
      node_js: '8'

    - stage: find-missing
      name: find-missing-main
      script:
        - npm run find-missing:core
        - npm run find-missing:prettier
        - npm run find-missing:lodash-fp

    - stage: find-missing
      name: find-missing-tests
      script:
        - npm run find-missing:ava
        - npm run find-missing:mocha

    - stage: find-missing
      name: find-missing-front
      script:
        - npm run find-missing:css-modules
        - npm run find-missing:flowtype
