language: node_js
sudo: false
node_js: '10'
cache: npm

stages:
  - lint
  - test
  - find-missing

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-plugin-node10
      script: npm run test:unit
      node_js: '10'
    - <<: *test
      name: test-plugin-node12
      node_js: '12'
    - <<: *test
      name: test-plugin-node8
      node_js: '8'

    - stage: find-missing
      name: find-missing-main
      script: npm run find-missing -- core prettier lodash-fp

    - stage: find-missing
      name: find-missing-tests
      script: npm run find-missing -- ava mocha

    - stage: find-missing
      name: find-missing-front
      script: npm run find-missing -- css-modules flowtype
